spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin-starter?serverTimezone=GMT%2B8
    username: root
    password: root

  jpa:
    database : MYSQL
    show-sql : false
    hibernate:
      ddl-auto : update
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect



